bot:
  token: 1458444160:AAH2dhjtcXiQuCzzKKkMdkHWXVG2wo0Thig
  access_key: 88dc4be0600c427f9488da198d507eae

db:
  redis:
    url: redis://localhost/?password=telestat
    host: localhost
    port: 6379
    password: telestat
  postgres: postgres://walther:walther@localhost:5432/trade_bot
